### PR TITLE
Update index of libraries

### PR DESCRIPTION
**Pull request by pauldraper**

### CODE REVIEW

**Comment by yurishkuro** [comment]
🎉 

I would rather keep then in the README. Essentially having this list is the only purpose of this repository, so why move the index into a separate click?

**Comment by tedsuo** [comment]
I agree! One stop shop.

**Comment by pauldraper** [comment]
> Essentially having this list is the only purpose of this repository

Well arguably there's contribution guidelines, badge info, and conferences. But sure, I'll change that.

**Comment by tedsuo** [comment]
Thanks @pauldraper, LGTM we can iterate from here.

**Pull request merged**
